#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = new Symfony\Component\Console\Application('Symfony Toolbelt', '1.0');
$app->add(new Symfony\Toolbelt\Installer\NewCommand());

$app->run();
