#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$appVersion = '1.0';

$app = new Symfony\Component\Console\Application('Symfony Toolbelt', $appVersion);
$app->add(new Symfony\Toolbelt\AboutCommand($appVersion));
$app->add(new Symfony\Toolbelt\Installer\NewCommand());

$app->setDefaultCommand('about');

$app->run();
